   --1. 
 SELECT STUDENT_NAME, STUDENT_ADDRESS
 FROM TB_STUDENT
 ORDER BY STUDENT_NAME ASC;
 
 --2.
 SELECT STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY 2 ASC;
 
 --3.
 SELECT  STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
 FROM TB_STUDENT
 WHERE  (STUDENT_ADDRESS LIKE '강원%' OR STUDENT_ADDRESS LIKE '경기도%' )AND SUBSTR(STUDENT_NO,1,1) = '9'
 ORDER BY STUDENT_NAME;

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = '005'
ORDER BY 2 ASC;

--5. 
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC , 1;

--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2;

--7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2;

--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_PROFESSOR P ON(C.DEPARTMENT_NO = P.DEPARTMENT_NO);

--9. 
SELECT S.STUDENT_NO "학번", S.STUDENT_NAME "학생 이름", ROUND(AVG(G.POINT),1) "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
WHERE S.DEPARTMENT_NO = '059'
GROUP BY S.STUDENT_NO,S.STUDENT_NAME;

--10.
SELECT DEPARTMENT_NAME, STUDENT_NAME, P.PROFESSOR_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO= S.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
WHERE S.STUDENT_NO = 'A313047';

--11.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_CLASS C ON(S.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007' AND CLASS_NAME = '인간관계론';

--12.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
LEFT JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR P ON(C.CLASS_NO = P.CLASS_NO)
WHERE CATEGORY = '예체능'AND PROFESSOR_NO IS NULL;

--13.
SELECT STUDENT_NAME "학생 이름", NVL(PROFESSOR_NAME,'지도교수 미지정')  "지도교수"
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과' 
ORDER BY S.STUDENT_NO ASC;

--14.
SELECT S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING ROUND(AVG(G.POINT),1) >= 4.0;

--15.
--환경조경학과 전공과목들의 과목 별 평점을 파악할 수 있는 SQL 문을 작성하시오. 단, 평점은
--소수점 1자리까지만 반올림하여 표시한다
SELECT C.CLASS_NO, C.CLASS_NAME, ROUND(AVG(G.POINT),1)
FROM TB_CLASS C
JOIN TB_GRADE G ON(C.CLASS_NO = G.CLASS_NO) 
JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '환경조경학과'
GROUP BY C.CLASS_NO, C.CLASS_NAME;


--16.춘 기술대학교에 다니고 있는 최경희 학생과 같은 과 학생들의 이름과 주소를 출력하는 SQL 문을 작성하시오.

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NO = (SELECT D.DEPARTMENT_NO
                         FROM TB_DEPARTMENT D 
                         JOIN TB_STUDENT S ON(D.DEPARTMENT_NO = S.DEPARTMENT_NO)
                         WHERE STUDENT_NAME = '최경희');

--17. 국어국문학과에서 총 평점이 가장 높은 학생의 이름과 학번을 표시하는 SQL 문을 작성하시오
--오류
SELECT SUM(POINT)
FROM TB_GRADE
GROUP BY STUDENT_NO;





SELECT S.STUDENT_NAME, S.STUDENT_NO
FROM TB_STUDENT S 
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NAME, S.STUDENT_NO
HAVING SUM(G.GRADE);


--18. 춘 기술대학교의 “환경조경학과”가 속한 같은 계열 학과들의 학과 별 전공과목 평점을 파악하
--기 위한 적절한 SQL 문을 찾아내시오. 단, 출력헤더는 “계열 학과명”, “전공평점”으로 표시되도록
--하고, 평점은 소수점 한 자리까지만 반올림하여 표시되도록 한다