 --1. 
 SELECT STUDENT_NAME, STUDENT_ADDRESS
 FROM TB_STUDENT
 ORDER BY STUDENT_NAME ASC;
 
 --2.
 SELECT STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY 2 ASC;
 
 --3.
 SELECT  STUDENT_NAME "학생이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
 FROM TB_STUDENT
 WHERE STUDENT_ADDRESS LIKE '강원%' AND STUDENT_ADDRESS LIKE '경기도%' 
 ORDER BY 1;

--4.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = '005'
ORDER BY 2 ASC;

--5. 
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC , 1;

--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2;

--7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY 2;

--8.
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_PROFESSOR P ON(C.DEPARTMENT_NO = P.DEPARTMENT_NO);

--9. --오류
SELECT S.STUDENT_NO "학번", S.STUDENT_NAME "학생 이름", ROUND(AVG(G.POINT),1) "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
GROUP BY S.STUDENT_NO
HAVING S.DEPARTMENT_NO = '059';

--10.
SELECT COACH_PROFESSOR_NO
FROM TB_STUDENT
WHERE STUDENT_NO = 'A313047'; --009

SELECT DEPARTMENT_NAME, STUDENT_NAME, P.PROFESSOR_NAME
FROM TB_DEPARTMENT D
JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
JOIN TB_PROFESSOR P ON(D.DEPARTMENT_NO = P.DEPARTMENT_NO)
WHERE P.PROFESSOR_NAME = (SELECT COACH_PROFESSOR_NO);

--11.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_CLASS C ON(S.DEPARTMENT_NO = C.DEPARTMENT_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007' AND CLASS_NAME = '인간관계론';

--12.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
LEFT JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR P ON(C.CLASS_NO = P.CLASS_NO)
WHERE CATEGORY = '예체능'AND PROFESSOR_NO IS NULL;

--13.
SELECT STUDENT_NAME "학생 이름", NVL(PROFESSOR_NAME,'지도교수 미지정')  "지도교수"
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON(S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과' 
ORDER BY S.STUDENT_NO ASC;

--14. 휴학생이 아닌 학생 중 평점이 4.0 이상인 학생을 찾아 그 학생의 학번, 이름, 학과 이름, 평
--점을 출력하는 SQL 문을 작성하시오. 단, 평점은 소수점 1자리까지만 반올림하여 표시한다
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME, POIT
FROM TB_STUDENT S
JOIN TB_DEPARTMNET D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO)
WHERE ABSENCE_YN = 'N' AND ROUND(AVG(POINT),1) >= 4.0;






FROM TB_STUDENT
WHERE STUDENT_NO = 'A313047');
