--1. 
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3
ORDER BY 1;

--3.
SELECT PROFESSOR_NAME , (100-  SUBSTR(PROFESSOR_SSN,1,2)) + 23 AS "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 2;

--4. 
SELECT SUBSTR(PROFESSOR_NAME,2) "이름"
FROM TB_PROFESSOR
ORDER BY "이름";

--5.
SELECT SUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ;


SELECT STUDENT_NAME , (100-  SUBSTR(STUDENT_SSN,1,2)) + 23  - AS "나이"
FROM TB_STUDENT;


--6. 

--9.
SELECT ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT ;

--13.
SELECT  DEPARTMENT_NO "학과코드 명", COUNT(ABSENCE_NO) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
HAVING ABSENCE_NO = 'Y';

